version: '3.4'

services:
  zookeeper:
    image: zookeeper:3.6.2
    hostname: zookeeper
    # restart: always
    configs:
    - source: zoo.cfg
      target: /conf/zoo.cfg
    volumes:
    - zookeeper-data:/tmp/zookeeper
    ports:
    - 2181:2181
    networks:
    - banking-network
    environment:
      ZOO_MY_ID: 1
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka-0:
    image: bitnami/kafka:2.7.0
    hostname: kafka-0
    # restart: always
    volumes:
    - 'kafka-data-0:/bitnami'
    ports:
    - '9092:9092'
    networks:
    - banking-network
    environment:
      KAFKA_BROKER_ID: 0
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
    - zookeeper

  kafka-1:
    image: bitnami/kafka:2.7.0
    hostname: kafka-1
    # restart: always
    volumes:
    - 'kafka-data-1:/bitnami'
    ports:
    - '9093:9092'
    networks:
    - banking-network
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
    - zookeeper

  kafka-2:
    image: bitnami/kafka:2.7.0
    hostname: kafka-2
    # restart: always
    volumes:
    - 'kafka-data-2:/bitnami'
    ports:
    - '9094:9092'
    networks:
    - banking-network
    environment:
      KAFKA_BROKER_ID: 2
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
    - zookeeper

  account-manager:
    build: account-manager
    hostname: account-manager
    image: account-manager
    environment:
      BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9093,kafka-2:9094
    networks:
    - banking-network
    depends_on:
    - kafka-0
    - kafka-1
    - kafka-2

  reporting-service:
    build: reporting-service
    hostname: reporting-service
    image: reporting-service
    environment:
      BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9093,kafka-2:9094
    networks:
    - banking-network
    depends_on:
    - kafka-0
    - kafka-1
    - kafka-2

  user-notification-service:
    build: user-notification-service
    hostname: user-notification-service
    image: user-notification-service
    environment:
      BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9093,kafka-2:9094
    networks:
    - banking-network
    depends_on:
    - kafka-0
    - kafka-1
    - kafka-2

  bank-api-service:
    build: bank-api-service
    hostname: bank-api-service
    image: bank-api-service
    environment:
      BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9093,kafka-2:9094
    networks:
    - banking-network
    depends_on:
    - kafka-0
    - kafka-1
    - kafka-2
    - account-manager
    - reporting-service
    - user-notification-service

networks:
  banking-network:
    name: banking-network
    driver: bridge

volumes:
  zookeeper-data:
    driver: local
  kafka-data-0:
    driver: local
  kafka-data-1:
    driver: local
  kafka-data-2:
    driver: local