apiVersion: v2
name: ingress
description: A Helm chart for Ingress Controller
type: application
version: 0.1.0
appVersion: 1.16.0
keywords:
  - ingress
  - nginx
  - api-gateway
home: https://github.com/s1lv10fr4gn4n1-org/cv-helm
maintainers:
  - name: S1lv10Fr4gn4n1
    url: https://github.com/S1lv10Fr4gn4n1
# dependencies:
#   - name: nginx-ingress
#     version: 1.36.0
#     repository: https://charts.helm.sh/stable