apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: long-job
        image: python:rc-slim
        command: ["python"]
        args: ["-c", "import time; print('starting'); time.sleep(30); print('done')"]
      restartPolicy: Never
  backoffLimit: 2

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cronjob
spec: # cronjob
  schedule: "* * * * *"
  jobTemplate:
    spec: # job
      template:
        spec: # pod
          containers:
          - name: long-job
            image: python:rc-slim
            command: ["python"]
            args: ["-c", "import time; print('starting'); time.sleep(30); print('done')"]
          restartPolicy: Never
      backoffLimit: 2