version: '3.1'

services:
  db:
    image: postgres:13.3-alpine
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080