version: '3.8'
services:
  # access the client docker-compose exec zookeeper1 zkCli.sh
  zookeeper1:
    image: zookeeper:3.6.2
    hostname: zookeeper1
    restart: always
    configs:
    - source: zoo.cfg
      target: /conf/zoo.cfg
    volumes:
    - /tmp/zookeeper:/tmp/zookeeper
    ports:
    - 2181:2181
    environment:
      ZOO_MY_ID: 1
      # ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181

  # zookeeper2:
  #   image: zookeeper:3.6.2
  #   hostname: zookeeper2
  #   restart: always
  #   ports:
  #     - 2182:2181
  #   environment:
  #     ZOO_MY_ID: 2
  #     ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181

  # zookeeper3:
  #   image: zookeeper:3.6.2
  #   hostname: zookeeper3
  #   restart: always
  #   ports:
  #     - 2183:2181
  #   environment:
  #     ZOO_MY_ID: 3
  #     ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181