version: '3.9'

services:
  postgres-user:
    image: postgres:alpine3.14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
      
  redis-user:
    image: redis:6.2.5-alpine
    command: redis-server --requirepass redis-user
    ports:
      - 6379:6379
    volumes:
      - redis-user-data:/data  
    

volumes:
  postgres-user-data:
  redis-user-data: