version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    hostname: photoapp-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  zipkin:
    image: openzipkin/zipkin:2
    hostname: photoapp-zipkin
    ports:
      - 9411:9411

  database:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: abacate
    volumes:
      - /var/tmp/mysql_photoapp:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8088:8080

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.12.5
    hostname: artifactory
    volumes:
      - /var/tmp/artifactory_data_v1:/var/opt/jfrog/artifactory/
      - /var/tmp/artifactory_data_v2/opt/jfrog/artifactory
    ports:
      - 7081:8081
      - 7082:8082