apiVersion: v1
kind: ConfigMap
metadata:
  name: global-database-config-v1
  namespace: default
data:
  DATABASE_URL: "http://database-server.com:3306"
  DATABASE_PASSWORD: "hello world"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: global-database-config-v2
  namespace: default
data:
  database.properties: |
    database.url=http://database-server.com:3306
    database.password=hello world